// Generated by https://quicktype.io
import { DateTime } from 'luxon';

export interface TimeSlot {
  duration:       Duration;
  availableSlots: number;
  capacity:       Capacity[];
}

export interface Capacity {
  resourceId:        number;
  availableCapacity: number;
}

export interface Duration {
  start: DateTime;
  end:   DateTime;
}

export interface TimeSlotDTO {
  duration:       DurationDTO;
  availableSlots: number;
  capacity:       Capacity[];
}

export interface CapacityDTO {
  resourceId:        number;
  availableCapacity: number;
}

export interface DurationDTO {
  start: string;
  end:   string;
}

export interface Time {
  hour: number;
  minute: number;
}